### ISSUE TITLE
500 Error on zbxwallboard.view

### ISSUE THREAD

**Issue by uKrease** [zbxwallboard/ZbxWallboard#12]
Hi, 

Version : Zabbix 5.4
Running on Ubuntu 18.04

I copied the files to the correct locations on the filesystem, activated the plugin via the Admin menu, however, when I click the Wallboard link in the main menu I get a page with an error:

This page isn’t working
zabbix.mycompany.com is currently unable to handle this request.
HTTP ERROR 500

My error log shows :
[Thu Apr 15 13:57:59.292783 2021] [php7:error] [pid 33597] [client 15.200.10.11:58944] PHP Fatal error:  Uncaught Error: Call to undefined function Modules\\ZbxWallboard\\select_config() in /usr/share/zabbix/modules/zbxwallboard/partials/CScreenWallboard.php:13\nStack trace:\n#0 /usr/share/zabbix/modules/zbxwallboard/views/monitoring.wallboard.view.php(67): Modules\\ZbxWallboard\\CScreenWallboard->__construct(Array)\n#1 /usr/share/zabbix/include/classes/mvc/CView.php(122): include('/usr/share/zabb...')\n#2 /usr/share/zabbix/include/classes/core/ZBase.php(636): CView->getOutput()\n#3 /usr/share/zabbix/include/classes/core/ZBase.php(565): ZBase->processResponseFinal(Object(CRouter), Object(Modules\\ZbxWallboard\\Actions\\ZbxWallboardProblemView))\n#4 /usr/share/zabbix/include/classes/core/ZBase.php(215): ZBase->processRequest(Object(CRouter))\n#5 /usr/share/zabbix/include/config.inc.php(25): ZBase->run('default')\n#6 /usr/share/zabbix/zabbix.php(22): require_once('/usr/share/zabb...')\n#7 {main}\n  thrown in /usr/share/zabbix/modules/zbxwallboard/partials/CScreenWallboard.php on line 13, referer: https://zabbix.mycompany.com/zabbix/zabbix.php?action=dashboard.view

Please advise how I can resolve this.

Thanks and have a groovy day.

**Comment by mjaepel** [comment]
See #9. wallboard as UI module  was tested with Zabbix 5.0. It's known that newer Zabbix releases changed dependent functions.
Seems that also newer minor releases in 5.0 are also affected. --> Issue #11 

I haven't the time for development currently. I will merge any working pull request. ;)
